spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(ZPUocTafr9B2xnWmL37RyeLPzzku6qbap9oXpQ5F8JE=)
    password: ENC(KJTTvFWL10rABIoKBDvGX/GCFZ837cc55s6y58DFQxw=)
    transport:
      protocol: smtp
    smtp:
      auth: true
      starttls:
        enable: true