spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: kjh22522252@gmail.com
    password: ENC(KJTTvFWL10rABIoKBDvGX/GCFZ837cc55s6y58DFQxw=)
    transport:
      protocol: smtp
    smtp:
      auth: true
      starttls:
        enable: true