spring:
  datasource:
    url: jdbc:oracle:thin:@fridgechefdev_high?TNS_ADMIN=./src/main/resources/Wallet_fridgeChefDev
    username: admin
    password: ENC(TaQurWARB9zfJ553U8MwSYPydWytzJREkfzDc14piIQ=)
    driver-class-name: oracle.jdbc.OracleDriver