### signup - cert
POST https://localhost/api/user/email/send
Content-Type: application/json

{
    "email": "admin@gmail.com"
}
### signup - cert verify
POST https://localhost/api/user/email/verify
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "code": 258438
}
