### 냉장고 등록
POST {{http-api}}/api/fridges/
Authorization: Bearer {{token}}
Content-Type: application/json

[
    {
        "ingredientName": "계란",
        "storage": "REFRIGERATION"
    },
    {
        "ingredientName": "라면",
        "storage": "TEMPERATURE"
    }
]


### 냉장고 재료 제거
DELETE {{http-api}}/api/fridges/ingredients
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "ingredientName": "라면"
}

### 냉장고 수정
PUT {{http-api}}/api/fridges/ingredients
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "라면",
    "category": "가공식품",
    "date": "2027-05-16"
}

### 냉장고 조회
GET {{http-api}}/api/fridges/
Authorization: Bearer {{token}}