
### access token
GET https://localhost/api/auth/access
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJ1c2VySWQiOiI0OTk2MWY1YS0zMDNhLTRhOTgtYjgzNC01OGUxMTg1OTRkNmQiLCJpYXQiOjE3MjYwMzUzMzQsImV4cCI6MTcyNjAzNzEzNH0.GmspcgjFx4SA9QVQl0YpkQd-hXyOfsIjMhPZKklMQmLVyqCGGzdArF0YrWWacnKSchwadSvTAMkWfnbIREzYMsqjtSJ7joUSRZLKUOwueiA6J_iUrU0FCjme4TPyR6IlbcU3GAvIew4iqJPhDEvPXrEwTSzG1_Id2YTcjKYyUAf0QU2XSQv6RxnmVeM9iWPFw6C2f5Ux-QSV30Yg3RncGnCRVePZ9a5WZyVumPTHlMphKcxDouRJHSAJ5i6Z19aK3rzVkphFz5okcofg9Zs7OrS-OeQRo3ap3R0lptrq0LR9JQpWZ-TM-Vpw7BslApYwfOzMp6ulHkut92F9fPVYiA

### refresh token
GET https://localhost/api/auth/refresh
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJ1c2VySWQiOiI1M2Y1OTRlZS05MmVjLTQwMjAtYmNmNy0yZjUyZjI0ZThiMWEiLCJpYXQiOjE3MjU5MTA1ODYsImV4cCI6MTcyNTkxMjM4Nn0.PeKL1X6HduXDiE4onNO2TNbImNMzAdfO4d5QBkDGGaDBbg2p2QKRxMfoWKWdjMAmPSOz0rp3780rUN_IbfeDgX5nAA3l-dBnfqpnx_Ol27B1YXlGUSFuBs6Z3Y8GlZC3wJpi4N5UBNH5OCM75vloOrrf6YS3hHaAFLodbzko6Dj8p4Y5d02D1QSnmKVVX9Pea5Jm91RJ-aEHD9YmhtOJgbqoIoBzl3AGC4cpjeuirgHKgYX4A7oxc9jLtVaC9i8iJ2idaLTJ31mNKi97-e-yn7aBvM7tDjFkQcKcm3a-iYnwgKwU0XI70Fbk9JTAvymMCgz3QvfugiV2w42-idKAbw