
### Get Current User test
GET https://localhost/api/user
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJ1c2VySWQiOiI4M2VlNjc1MC00ODUxLTRlYzMtYTdmOC0wZDAxNWQzMzY2OWUiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTcyNzEwMjg5MiwiZXhwIjoxNzI3MTA0NjkyfQ.JJ4M8lnY91FFQyKM4JxogakaLP2ja84C4PUkZbsXCGWOHWP_FN5X6sCwvKzhBe4uiXSV1KAJskNL49_2Pnp6kOVxo4w4ecowSwEQ38TltMbCvA5h41V6dmtE6ccQDp_Cg7vHUInpUoo7pbGis-9pz6jih_k1OLA5aBpKEKXBOJqKLurntdagNKGz0W4sZBo_XeioNWAFnH-FcRsPZQyvdhVxgd1cvoCcq4YaBVSAVAumIZDn6YXmXXYIc_xi6DlbgHptqYNIWLVBlqNTMphiaDehcTNcVbIe2nv7cdSA9Az7qVD1Effmb5xeQWQOeN0fENveK7DaEi6teYrXkmT5XA


### Get Current User test
GET https://fridgebe.site/api/user
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJ1c2VySWQiOiIxODAzM2UzZi0yZjE1LTQ0MGItOGJkMi0yODRjMjU5NjQ2YTEiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTcyNzE0Mjg1NSwiZXhwIjoxNzI3MTQ0NjU1fQ.dpGl6rvH1Z9uCIcR8MiaItgSduiWFsI3ZfSNA4WTP9nOZ8zHhvcgFSInE8WvC4-Lk0MxR5Md4Ge-yyG2rBhNYq7LJUVdISlnDq44Tbd9xIoJuNEkpO5yiluO8dXB7aML6MbOKYd7Li-Gd-6tyYlxVefYU-YGUAzLOHkDDVbq4ks0BJ8PPc4xpcggUxATD63SqTli3rE2MYK3TN-Kgzi3nw2d7POfe3wTsQ5o9FvYABUQY4cGh2LMvQibTNpbPgik9P0qWxrDvhnKOdicnSBqliE4AjcK3zg_o-TRa-V5-9DaGGJUndM9anaUwkrbTTVzek074D8UkpGE49m35Rok2g



