
### Get Current User test
GET https://localhost/api/user
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJ1c2VySWQiOiI4M2VlNjc1MC00ODUxLTRlYzMtYTdmOC0wZDAxNWQzMzY2OWUiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTcyNzEwMjg5MiwiZXhwIjoxNzI3MTA0NjkyfQ.JJ4M8lnY91FFQyKM4JxogakaLP2ja84C4PUkZbsXCGWOHWP_FN5X6sCwvKzhBe4uiXSV1KAJskNL49_2Pnp6kOVxo4w4ecowSwEQ38TltMbCvA5h41V6dmtE6ccQDp_Cg7vHUInpUoo7pbGis-9pz6jih_k1OLA5aBpKEKXBOJqKLurntdagNKGz0W4sZBo_XeioNWAFnH-FcRsPZQyvdhVxgd1cvoCcq4YaBVSAVAumIZDn6YXmXXYIc_xi6DlbgHptqYNIWLVBlqNTMphiaDehcTNcVbIe2nv7cdSA9Az7qVD1Effmb5xeQWQOeN0fENveK7DaEi6teYrXkmT5XA




