spring:
  datasource:
    url: jdbc:oracle:thin:@fridgechef_high?TNS_ADMIN=./src/main/resources/Wallet_fridgeChef
    username: ADMIN
    password: ENC(mE7S46BWUTZS1ES17svBz72u6sA6c0No)
    driver-class-name: oracle.jdbc.OracleDriver