name: 'Add Labels on Push or PR'

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  add-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment variables
        run: |
          echo "DOMAIN_TAGS=image,user,board,security,recipe,mail,ingredient,tag,feat" >> $GITHUB_ENV
          echo "SETTING_TAGS=ci/cd,config,gradle,build,bug,action" >> $GITHUB_ENV
          echo "CODE_TAGS=refactor,update,style" >> $GITHUB_ENV

      - name: Checkout the PR to ensure all references are available
        run: |
          git fetch origin $BASE_BRANCH --prune
          git checkout $BASE_BRANCH

      - name: Get commits
        id: get_commits
        run: |
          echo "Event Name: ${{ github.event_name }}"

          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          BASE_BRANCH="${{ github.event.pull_request.base.ref }}"
          echo "Base Branch for PR: $BASE_BRANCH"
          
          # Fetch the base branch and PR branch
          git fetch origin $BASE_BRANCH
          git fetch origin ${{ github.head_ref }}
          
          # Checkout the PR base branch
          git checkout $BASE_BRANCH
          
          # Get the commits from the base branch to the current commit
          COMMITS=$(git log --oneline "${BASE_BRANCH}..${{ github.sha }}" --pretty=format:"%s")
          echo "Commits from $BASE_BRANCH to current commit: $COMMITS"
          else
          BASE_BRANCH="${{ github.ref }}"
          echo "Base Branch for Push: $BASE_BRANCH"
          
          COMMITS=$(git log --oneline "${BASE_BRANCH}~1..${{ github.sha }}" --pretty=format:"%s")
          echo "Commits from $BASE_BRANCH to current commit: $COMMITS"
          fi
          
          echo "COMMITS=$COMMITS" >> $GITHUB_ENV
      - name: Display commits list print
        run: |
          echo "Commits: ${{ env.COMMITS }}"
          echo "Split Commits:"
          for commit in $COMMITS; do
            echo "Commit: $commit"
          done
      - name: Display commits
        run: |
          # Use printf to handle multiline variables safely
          printf "Commits: %s\n" "${{ env.COMMITS }}"

      - name: Determine labels based on commits
        id: determine_labels
        run: |
            DOMAIN_TAGS=(${DOMAIN_TAGS//,/ })
            SETTING_TAGS=(${SETTING_TAGS//,/ })
            CODE_TAGS=(${CODE_TAGS//,/ })
            
            LABELS=()
            for COMMIT in $COMMITS; do
              echo "Checking commit: $COMMIT"
              for TAG in "${DOMAIN_TAGS[@]}"; do
                if [[ "$COMMIT" == *"$TAG"* ]]; then
                  LABELS+=("$TAG")
                  echo "Matched DOMAIN_TAG: $TAG"
                  if [ ${#LABELS[@]} -ge 5 ]; then break 2; fi
                fi
              done
            done
            
            if [ ${#LABELS[@]} -lt 5 ]; then
              for TAG in "${SETTING_TAGS[@]}"; do
                if [[ "$COMMIT" == *"$TAG"* ]]; then
                  LABELS+=("$TAG")
                  echo "Matched SETTING_TAG: $TAG"
                  if [ ${#LABELS[@]} -ge 5 ]; then break; fi
                fi
              done
            fi
            
            if [ ${#LABELS[@]} -lt 5 ]; then
              for TAG in "${CODE_TAGS[@]}"; do
                if [[ "$COMMIT" == *"$TAG"* ]]; then
                  LABELS+=("$TAG")
                  echo "Matched CODE_TAG: $TAG"
                  if [ ${#LABELS[@]} -ge 5 ]; then break; fi
                fi
              done
            fi
            
            FINAL_LABELS=$(IFS=,; echo "${LABELS[*]}")
            echo "FINAL_LABELS=$FINAL_LABELS" >> $GITHUB_ENV

      - name: Create missing labels
        run: |
          IFS=',' read -r -a LABEL_ARRAY <<< "${{ env.FINAL_LABELS }}"
          for LABEL in "${LABEL_ARRAY[@]}"; do
            if ! gh label list | grep -q "$LABEL"; then
              echo "Creating label: $LABEL"
              gh label create "$LABEL" --color "$(printf '#%06X\n' $((RANDOM%16777215)))"
            fi
          done

      - name: Add labels to PR
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "Adding labels: ${{ env.FINAL_LABELS }} to PR #${{ github.event.pull_request.number }}"
            if gh pr edit ${{ github.event.pull_request.number }} --add-label "${{ env.FINAL_LABELS }}"; then
              echo "Labels added successfully."
            else
              echo "Failed to add labels."
            fi
          else
            echo "Not a pull request event, no labels added."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Display final labels
        run: |
          echo "FINAL_LABELS: ${{ env.FINAL_LABELS }}"
