name: 'Add Labels on Push or PR'

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  add-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # 모든 히스토리를 가져옵니다.

      - name: Fetch all branches
        run: |
          # PR 소스 브랜치와 타겟 브랜치를 가져옵니다.
          git fetch origin ${{ github.base_ref }} --prune
          git fetch origin ${{ github.head_ref }} --prune

      - name: Set up environment variables
        run: |
          echo "DOMAIN_TAGS=image,user,board,security,recipe,mail,ingredient,tag,feat" >> $GITHUB_ENV
          echo "SETTING_TAGS=ci/cd,config,gradle,build,bug,action" >> $GITHUB_ENV
          echo "CODE_TAGS=refactor,update,style" >> $GITHUB_ENV

      - name: Get commits between branches
        run: |
          BASE_BRANCH=${{ github.base_ref }}  # 예: main
          PR_BRANCH=${{ github.head_ref }}    # PR 브랜치 (예: action/tag)
          
          echo "Checking out $BASE_BRANCH"
          git checkout $BASE_BRANCH
          
          echo "Commits from $BASE_BRANCH to $PR_BRANCH:"
          COMMITS=$(git log --no-merges --oneline origin/$BASE_BRANCH..origin/$PR_BRANCH --pretty=format:"%s")
          echo "Commits: \"$COMMITS\""
          
          # 커밋 메시지를 $GITHUB_ENV에 저장
          echo "COMMITS=\"$COMMITS\"" >> $GITHUB_ENV

      - name: Checkout the PR to ensure all references are available
        run: |
          git fetch origin $BASE_BRANCH --prune
          git checkout $BASE_BRANCH

      - name: Display commits
        run: |
          printf "Commits: %s\n" "${{ env.COMMITS }}"

      - name: Determine labels based on commits
        id: determine_labels
        run: |
          DOMAIN_TAGS=(${DOMAIN_TAGS//,/ })
          SETTING_TAGS=(${SETTING_TAGS//,/ })
          CODE_TAGS=(${CODE_TAGS//,/ })
          
          LABELS=()
          for COMMIT in $COMMITS; do
            echo "Checking commit: $COMMIT"
            for TAG in "${DOMAIN_TAGS[@]}"; do
              if [[ "$COMMIT" == *"$TAG"* ]]; then
                LABELS+=("$TAG")
                echo "Matched DOMAIN_TAG: $TAG"
                if [ ${#LABELS[@]} -ge 5 ]; then break 2; fi
              fi
            done
          done
          
          if [ ${#LABELS[@]} -lt 5 ]; then
            for TAG in "${SETTING_TAGS[@]}"; do
              if [[ "$COMMIT" == *"$TAG"* ]]; then
                LABELS+=("$TAG")
                echo "Matched SETTING_TAG: $TAG"
                if [ ${#LABELS[@]} -ge 5 ]; then break; fi
              fi
            done
          fi
          
          if [ ${#LABELS[@]} -lt 5 ]; then
            for TAG in "${CODE_TAGS[@]}"; do
              if [[ "$COMMIT" == *"$TAG"* ]]; then
                LABELS+=("$TAG")
                echo "Matched CODE_TAG: $TAG"
                if [ ${#LABELS[@]} -ge 5 ]; then break; fi
              fi
            done
          fi
          
          FINAL_LABELS=$(IFS=,; echo "${LABELS[*]}")
          echo "FINAL_LABELS=$FINAL_LABELS" >> $GITHUB_ENV

      - name: Create missing labels
        run: |
          IFS=',' read -r -a LABEL_ARRAY <<< "${{ env.FINAL_LABELS }}"
          for LABEL in "${LABEL_ARRAY[@]}"; do
            if ! gh label list | grep -q "$LABEL"; then
              echo "Creating label: $LABEL"
              gh label create "$LABEL" --color "$(printf '#%06X\n' $((RANDOM%16777215)))"
            fi
          done

      - name: Add labels to PR
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "Adding labels: ${{ env.FINAL_LABELS }} to PR #${{ github.event.pull_request.number }}"
            if gh pr edit ${{ github.event.pull_request.number }} --add-label "${{ env.FINAL_LABELS }}"; then
              echo "Labels added successfully."
            else
              echo "Failed to add labels."
            fi
          else
            echo "Not a pull request event, no labels added."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Display final labels
        run: |
          echo "FINAL_LABELS: ${{ env.FINAL_LABELS }}"
